import { chmodSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { getRuntimeDir } from "../daemon/paths.js";

export const CLAUDE_ENV_PATH = join(getRuntimeDir(), "claude.env");

export function writeClaudeEnvFile(env: NodeJS.ProcessEnv = process.env): {
  path: string;
  variableNames: string[];
} {
  const variableNames = Object.keys(env)
    .filter((key) => isAgentEnvVar(key) && env[key])
    .sort();

  const lines = [
    "# Generated by raven-ts init.",
    "# Background services import these Claude/Codex auth values when supported.",
    ...variableNames.map((key) => `${key}=${quoteEnvValue(env[key] ?? "")}`),
    "",
  ];

  mkdirSync(dirname(CLAUDE_ENV_PATH), { recursive: true });
  writeFileSync(CLAUDE_ENV_PATH, lines.join("\n"), { mode: 0o600 });
  chmodSync(CLAUDE_ENV_PATH, 0o600);

  return { path: CLAUDE_ENV_PATH, variableNames };
}

export function ensureClaudeEnvFile(): { path: string; created: boolean } {
  if (existsSync(CLAUDE_ENV_PATH)) {
    return { path: CLAUDE_ENV_PATH, created: false };
  }
  writeClaudeEnvFile();
  return { path: CLAUDE_ENV_PATH, created: true };
}

function quoteEnvValue(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function isAgentEnvVar(key: string): boolean {
  return key.startsWith("ANTHROPIC_") || key.startsWith("OPENAI_") || key.startsWith("CODEX_");
}
