import { chmodSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { homedir } from "os";
import { dirname, join } from "path";

export const CLAUDE_ENV_PATH = join(homedir(), ".config", "cc-ys", "claude.env");

export function writeClaudeEnvFile(env: NodeJS.ProcessEnv = process.env): {
  path: string;
  variableNames: string[];
} {
  const variableNames = Object.keys(env)
    .filter((key) => key.startsWith("ANTHROPIC_") && env[key])
    .sort();

  const lines = [
    "# Generated by cc-ys init.",
    "# systemd imports this file through EnvironmentFile.",
    ...variableNames.map((key) => `${key}=${quoteEnvValue(env[key] ?? "")}`),
    "",
  ];

  mkdirSync(dirname(CLAUDE_ENV_PATH), { recursive: true });
  writeFileSync(CLAUDE_ENV_PATH, lines.join("\n"), { mode: 0o600 });
  chmodSync(CLAUDE_ENV_PATH, 0o600);

  return { path: CLAUDE_ENV_PATH, variableNames };
}

export function ensureClaudeEnvFile(): { path: string; created: boolean } {
  if (existsSync(CLAUDE_ENV_PATH)) {
    return { path: CLAUDE_ENV_PATH, created: false };
  }
  writeClaudeEnvFile();
  return { path: CLAUDE_ENV_PATH, created: true };
}

function quoteEnvValue(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
